GET http://localhost:8080/albums


###
POST http://localhost:8080/albums
Content-Type: application/json

{
    "title": "foo",
    "artist": "hii",
    "price": 50.00
}

###
GET http://localhost:8080/albums/1